apiVersion: v1
kind: Route
metadata:
  name: secured-edge-route
spec:
  host: secured-edge-route.openshift.citrix-cic.com
  path: "/"
  to:
    kind: Service
    name: svc-apache-multi-http
  tls:
    termination: edge

    key: |-                      
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEArcLdl+wlEsV7Ym7wfUIbin3Gvp9T1trqaQ2EY6H8GVCztIbP
      68IPPoGjQLrLRy42dyxJdtkTEnifkp7RGAaXv/iGQxD4kPEy8rakTvQG7Ecoj6Eg
      oc0BeaoQmfo9fT4BVSree3yjk5MOZcqSOmQitm4G8nZfukK9e0w6Kmz4k1dIDjVQ
      YW8RkstxgtPj5HYq49jqjKpuVLkINckM9YSULqmrRd14Hfm6XkjwE4AcJlGFXwjo
      CSknD5Fg3PLPWR4CSBPM/9KxC/58NCOZKOS+aD/BOYHWJPoDKSxBMQlyh47ZjcAp
      s2+WQWc0x9/BL8aHj3D9q3DGbUWlfCGDxKpRjwIDAQABAoIBABju6VUvcXJsG/RX
      7vJKViFdQvN/cUxXRWOlqOWTDNWlGuRAo/00b3OMrpxPMXQZUX9wP2pqY6422M71
      MxO7fnLxenKNMN27fpANXS5nHccxvsQ9Xq1Y+Wk32gH+QmyCRTavXBVkISS/6UT5
      +FmgnMqIpz6LddkIUqAqo/4KfPDHTOvbON1Qvd4UE5A2nYhN2GXTe8KdjHsqZX8U
      BLjqPLWBrZbgh0/CjayuEjpsfaibPuzm+ovP/UNZIxBJ54ToppDVmP0Xs5weg5cj
      vj2q1SIX/M6An8xmZPu2ZVsT9pYe+f1W+GB3/BPtQ7LgTWC0xyCXXBWXcsqeuNe9
      znXEVQECgYEA1JiAMaqYTk/qgI6PRPWBXHY9/8SITejY/ZmomMeJUO+BBYOdCtX3
      aLk5uqX8tIW1lEcpeiI2ze5De0F+Vr6A4dHf1Se2reJW1g0iABvfzN4va7sSP//U
      77oqtvh6O8KYQ8gQlMhIjSDRje69nrxTzD10PV0XMS5XNCpwguLYUy8CgYEA0Tyl
      M9L/ZqDMNRx/e5LaN9eqxZfcBrQ1ZJ8ia1WJbbiBhrXH04VfRZQwO2c7iQbVA0YZ
      X6ukPrAaN6ve+HkSMpscuZhH/Bb6Fietf1CAdQ2SfLw/EWFo/EqnWZ2uo0abxJYT
      K0+KAGsjN/6XZupMFJKZpJ9EjowX1d3CsUuVz6ECgYAlWoIzt9C4+cuvON0tdaF8
      GH5+QQ7d+YqezG/WIEEdSme2C1D9hWjKKrlc9Ss4oMGtwu8juX09o56RuokzPpew
      lcqpTigH11wAkiAmOr+Q5H0aha0IN7A3StOUgIYhl+hfCHj5W1N8EIchVBBXIqnq
      meWhnoijqIvD660HIkp2GwKBgAV8J4CCSXuxP2ktBBKDOQE5wBpJ7tSmKLgoi8hw
      h5e+vHaBkWl0F5lFVzZXcHIZIcBiOAwP/dA+4ZEQClpNIjL9afVbjpeHKqsmAyBR
      RezLnEl0zdpwyUXD1zs8LPXOxgqTPJFoFmAIbvXq0KE8Bx6K8UglfLCX75AFrjLj
      nlvBAoGBALzx8w8G9B2IuVP3D+XraW+nD/r963gg31MkF5KN+rilJy/620QaxFFi
      5qJMEGf7NexJgOWy4dhBJyN7wmtjXlc1VIznOKtZeASHu3gWXPA/naO6/eReNWX2
      voyUjb9VwF6F1kpertNnbJYIR7UQovJTtLO74TKVIRiuErm1sZXe
      -----END RSA PRIVATE KEY-----

    certificate: |-              
      -----BEGIN CERTIFICATE-----
      MIIDbzCCAlcCCQDVaVapF+wInzANBgkqhkiG9w0BAQsFADB6MQswCQYDVQQGEwJJ
      TjESMBAGA1UECAwJS2FybmF0YWthMRIwEAYDVQQHDAlCYW5nYWxvcmUxDzANBgNV
      BAoMBkNpdHJpeDEMMAoGA1UECwwDRGV2MSQwIgYDVQQDDBtjYS5vcGVuc2hpZnQu
      Y2l0cml4LWNpYy5jb20wHhcNMTkwMzI0MTQzNjIyWhcNMjIwMTExMTQzNjIyWjB5
      MQswCQYDVQQGEwJJTjESMBAGA1UECAwJS2FybmF0YWthMRIwEAYDVQQHDAlCYW5n
      YWxvcmUxDzANBgNVBAoMBkNpdHJpeDEMMAoGA1UECwwDRGV2MSMwIQYDVQQDDBoq
      Lm9wZW5zaGlmdC5jaXRyaXgtY2ljLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
      ADCCAQoCggEBANYwWQyqnUmdt7yAjbkbIOCm03saADOu1ayBzuaw8vdbenVQsVPj
      Fm2Umhe8L4MRo7/TN6S1+l9wZSWyMCQaxKprYWUn+IhtaUn2Cg8Tz72F54Tsol0+
      fyPbJTY6F8QBHfCPMvCdye8DkWe+uXCUV9381VYYn7FSqhNfv9VhpMBdet8KfcTE
      c7LBShqdQD2CJmERDVK/iMa+K0oq0w4JBdaQ9TbzZXPOMFy1y92mOkUqSjPwsHOC
      pEdr3uETGybqx3w/w/cf78dT3tZGFBSfbvHcsDSUBQ62t0ylAn7S+8vJad86IDSG
      2/HqnRpn5QTuIRMDsHHEKkAVsGo0i1Yi638CAwEAATANBgkqhkiG9w0BAQsFAAOC
      AQEAeikL6ktcdotFwQfHLVvGOgATfFr7lSosc5QD/OXEDCn2Z1VzPkNPkgk+hCnU
      UfpqofUEfuA7e+L669h0dfdb0NupG+XpJERuE/2zeGYt0YhH3bdz9BMNbj1j465v
      tqzaSeAwLU+yuzRzjL9bY3slz7ItN8/jz+4/x4PGCaHNbGVQI1MaDGn7zL+3z/nt
      WfKyrMSQv0bmTIAiKxD69DsLBdagd0W9++YG05ikWpbcDUqO9dAFNH6kh/fOoJQA
      0xStmeEHUoMouXDvBcgHonmN4Fw+S0WR6sG/UpOmKOxH3dzC5EK0WKXDPOwn7279
      GbqIML4OOBN+8pwByFp7T+3xAQ==
      -----END CERTIFICATE-----
