{{- if .Values.ns_fluentbit_logproxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input.conf
    @INCLUDE output.conf

  input.conf: |
    [INPUT]
        Name              ns_lstream
        Tag               transaction_logs
        Listen            0.0.0.0

  output.conf: |
    [OUTPUT]
{{- if (empty .Values.ns_fluentbit_logproxy.output) }}
        Name            stdout
        Match           *
{{- else}}
{{ .Values.ns_fluentbit_logproxy.output | indent 9 }}
{{- end }}
{{- end }}

{{- if .Values.ns_logproxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logproxy-config
data:
  lstreamd.conf: |-
    {
        "RecordType": {
            "HTTP": "anomalous",
            "TCP": "none",
            "SWG": "all",
            "VPN": "all",
            "NGS": "all",
            "ICA": "all",
            "APPFW": "none",
            "BOT": "none",
            "VIDEOOPT": "none",
            "BURST_CQA": "none",
            "SLA": "none"
        },
        "ProcessAlways": "no",
        "FileSizeMax": "40",
        "ProcessYieldTimeOut": "500",
        "FileStorageLimit": "1000",
{{- if .Values.ns_tracing.enabled }}
        "EnableTracing": "yes",
        "TracingServer": "zipkin:9411/api/v1/spans",
{{- end }}
        "SkipAvro": "no"
    }
{{- end }}
