# Default values for citrix-k8-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# image contains information needed to fetch CIC image
image:
  #repository: quay.io/citrix/citrix-k8s-ingress-controller 
  #tag: 1.1.1
  repository: 10.217.212.108:5000/citrix-ingress-controller
  tag: 1.0.1
  pullPolicy: Always
#loginFileName is secret file for NetScaler login
loginFileName:
# nsIP is NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled)
nsIP: x.x.x.x

logLevel: DEBUG
# license accept should be 'yes' to run Citrix Ingress Controller
license:
   accept: no
# nsPort is port for NetScaler NITRO
nsPort: 443
# nsProtocol is protocol for NetScaler NITRO
nsProtocol: HTTPS
# logLevel is to set level of CIC Logs
logLevel: DEBUG
# kubernetesURL is for registering events to kubeapi server
kubernetesURL:
# ingressClass is the name of the Ingress Class
ingressClass:
#nodeWatch is used for automatic route configuration on NetScaler towards the pod network
nodeWatch: false
# exporter conatins information of prometheus-exporter
exporter:
  require: 0
  image:
       repository: quay.io/citrix/netscaler-metrics-exporter
       tag: v1.0.4
       pullPolicy: Always
  ports:
       containerPort: 8888

ns_logproxy:
  enabled: false
  # Define in Fluent-bit output format.
  #output: |
  #  Name            kafka
  #  Match           *
  #  Brokers         dp-kafka-cp-kafka-headless:9092
  #  Topics          nshttp-logs
  #  rdkafka.log.connection.close false
  #  rdkafka.queue.buffering.max.ms 1000
  #  rdkafka.queue.buffering.max.messages 30000
  #  rdkafka.request.required.acks 0
  #  Retry_Limit     1
